// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/betting.proto

package betting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BetSide       string                 `protobuf:"bytes,2,opt,name=BetSide,proto3" json:"BetSide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetRequest) Reset() {
	*x = BetRequest{}
	mi := &file_proto_betting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRequest) ProtoMessage() {}

func (x *BetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_betting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRequest.ProtoReflect.Descriptor instead.
func (*BetRequest) Descriptor() ([]byte, []int) {
	return file_proto_betting_proto_rawDescGZIP(), []int{0}
}

func (x *BetRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BetRequest) GetBetSide() string {
	if x != nil {
		return x.BetSide
	}
	return ""
}

type BetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetResult     string                 `protobuf:"bytes,1,opt,name=BetResult,proto3" json:"BetResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetResponse) Reset() {
	*x = BetResponse{}
	mi := &file_proto_betting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResponse) ProtoMessage() {}

func (x *BetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_betting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResponse.ProtoReflect.Descriptor instead.
func (*BetResponse) Descriptor() ([]byte, []int) {
	return file_proto_betting_proto_rawDescGZIP(), []int{1}
}

func (x *BetResponse) GetBetResult() string {
	if x != nil {
		return x.BetResult
	}
	return ""
}

type BetSettlement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	BetResult     string                 `protobuf:"bytes,3,opt,name=betResult,proto3" json:"betResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetSettlement) Reset() {
	*x = BetSettlement{}
	mi := &file_proto_betting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetSettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetSettlement) ProtoMessage() {}

func (x *BetSettlement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_betting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetSettlement.ProtoReflect.Descriptor instead.
func (*BetSettlement) Descriptor() ([]byte, []int) {
	return file_proto_betting_proto_rawDescGZIP(), []int{2}
}

func (x *BetSettlement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BetSettlement) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BetSettlement) GetBetResult() string {
	if x != nil {
		return x.BetResult
	}
	return ""
}

var File_proto_betting_proto protoreflect.FileDescriptor

const file_proto_betting_proto_rawDesc = "" +
	"\n" +
	"\x13proto/betting.proto\x12\abetting\">\n" +
	"\n" +
	"BetRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x18\n" +
	"\aBetSide\x18\x02 \x01(\tR\aBetSide\"+\n" +
	"\vBetResponse\x12\x1c\n" +
	"\tBetResult\x18\x01 \x01(\tR\tBetResult\"U\n" +
	"\rBetSettlement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x1c\n" +
	"\tbetResult\x18\x03 \x01(\tR\tbetResult2G\n" +
	"\x0eBettingService\x125\n" +
	"\bPlaceBet\x12\x13.betting.BetRequest\x1a\x14.betting.BetResponseB\x1eZ\x1cshared/proto/betting;bettingb\x06proto3"

var (
	file_proto_betting_proto_rawDescOnce sync.Once
	file_proto_betting_proto_rawDescData []byte
)

func file_proto_betting_proto_rawDescGZIP() []byte {
	file_proto_betting_proto_rawDescOnce.Do(func() {
		file_proto_betting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_betting_proto_rawDesc), len(file_proto_betting_proto_rawDesc)))
	})
	return file_proto_betting_proto_rawDescData
}

var file_proto_betting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_betting_proto_goTypes = []any{
	(*BetRequest)(nil),    // 0: betting.BetRequest
	(*BetResponse)(nil),   // 1: betting.BetResponse
	(*BetSettlement)(nil), // 2: betting.BetSettlement
}
var file_proto_betting_proto_depIdxs = []int32{
	0, // 0: betting.BettingService.PlaceBet:input_type -> betting.BetRequest
	1, // 1: betting.BettingService.PlaceBet:output_type -> betting.BetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_betting_proto_init() }
func file_proto_betting_proto_init() {
	if File_proto_betting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_betting_proto_rawDesc), len(file_proto_betting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_betting_proto_goTypes,
		DependencyIndexes: file_proto_betting_proto_depIdxs,
		MessageInfos:      file_proto_betting_proto_msgTypes,
	}.Build()
	File_proto_betting_proto = out.File
	file_proto_betting_proto_goTypes = nil
	file_proto_betting_proto_depIdxs = nil
}
