// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_balance_proto protoreflect.FileDescriptor

const file_proto_balance_proto_rawDesc = "" +
	"\n" +
	"\x13proto/balance.proto\x12\abalance\"+\n" +
	"\x11GetBalanceRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance2W\n" +
	"\x0eBalanceService\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.balance.GetBalanceRequest\x1a\x1b.balance.GetBalanceResponseB\x1eZ\x1cshared/proto/balance;balanceb\x06proto3"

var (
	file_proto_balance_proto_rawDescOnce sync.Once
	file_proto_balance_proto_rawDescData []byte
)

func file_proto_balance_proto_rawDescGZIP() []byte {
	file_proto_balance_proto_rawDescOnce.Do(func() {
		file_proto_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)))
	})
	return file_proto_balance_proto_rawDescData
}

var file_proto_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_balance_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),  // 0: balance.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 1: balance.GetBalanceResponse
}
var file_proto_balance_proto_depIdxs = []int32{
	0, // 0: balance.BalanceService.GetBalance:input_type -> balance.GetBalanceRequest
	1, // 1: balance.BalanceService.GetBalance:output_type -> balance.GetBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_balance_proto_init() }
func file_proto_balance_proto_init() {
	if File_proto_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_balance_proto_goTypes,
		DependencyIndexes: file_proto_balance_proto_depIdxs,
		MessageInfos:      file_proto_balance_proto_msgTypes,
	}.Build()
	File_proto_balance_proto = out.File
	file_proto_balance_proto_goTypes = nil
	file_proto_balance_proto_depIdxs = nil
}
